services:
  app:
    build:
      context: "../.."
      dockerfile: Dockerfile
    ports:
      - "8080:3000"

  database:
    build:
      context: ../../database/dev
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
